# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-OpenSSL-RSA
version:      0.25
version_from: RSA.pm
installdirs:  site
requires:
    Crypt::OpenSSL::Random:        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
